name: Juscang
description: "Layanan Komunikasi Telepon Antar Perangkat"
version: 6.8.5

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  flutter_local_notifications: ^18.0.1
  agora_rtc_engine: ^6.3.2
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_database: ^11.1.6
  firebase_messaging: ^15.1.5
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/SelesaiTelpon.mp3
    - assets/MulaiTelpon.mp3